### ISSUE TITLE
How to import accimage when my computer just has cpu?And the system is win10

### ISSUE THREAD

**Issue by SRN200722** [pytorch/accimage#37] opened 2021-09-18 12:29 UTC

**Comment by willprice** [comment] 2021-09-18 12:30
Duplicate of #23.
Windows installs are not currently supported. I don't have the bandwidth to do so. Happy to accept PRs that add Windows support though.

**Closed as completed by willprice** 2021-09-18 12:30 UTC

**Comment by SRN200722** [comment] 2021-09-18 12:32
view it on GitHub




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Will ***@***.***&gt;; 
发送时间: 2021年9月18日(星期六) 晚上8:30
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [pytorch/accimage] How to import accimage when my computer just has cpu?And the system is win10 (#37)





 
Closed #37.
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by SRN200722** [comment] 2021-09-18 12:37
OK,Thanks.But I must run swin-transformer,can I delete anything about it?




------------------ 原始邮件 ------------------
发件人: "Will ***@***.***&gt;; 
发送时间: 2021年9月18日(星期六) 晚上8:30
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [pytorch/accimage] How to import accimage when my computer just has cpu?And the system is win10 (#37)





 
Closed #37.
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by willprice** [comment] 2021-09-18 12:39
AccImage is a drop in replace for PIL. I suggest you use Pillow-SIMD (https://github.com/uploadcare/pillow-simd), failing that, just the vanilla Pillow package.

**Comment by SRN200722** [comment] 2021-09-18 12:41
Thank you for your suggestion




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Will ***@***.***&gt;; 
发送时间: 2021年9月18日(星期六) 晚上8:39
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [pytorch/accimage] How to import accimage when my computer just has cpu?And the system is win10 (#37)





 
AccImage is a drop in replace for PIL. I suggest you use Pillow-SIMD (https://github.com/uploadcare/pillow-simd), failing that, just the vanilla Pillow package.
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
